[package]
name = "frqstbite/object-pool"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
