[package]
name = "frqstbite/object-pool"
description = "The last object pool implementation you'll ever need."
authors = ["frqstbite"]
version = "1.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
