name: documentation

on:
  pull_request:
  push:
    branches: [main]
env:
  HUSKY: 0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: "11.x"
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
      - run: pnpm install --ignore-scripts
      - run: pnpm moonwave build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: build
  # Deploy if this isn't a CI run
  deploy:
    needs: build
    if: ${{ github.event_name == 'push' }} 
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
