name: release

on:
  push:
    branches: [main]
env:
  HUSKY: 0
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
      - uses: CompeyDev/setup-rokit@v0.2.1
      - run: rokit install --no-trust-check
      - run: |
          pnpm dlx                                               \
            --package=semantic-release                           \
            --package=conventional-changelog-conventionalcommits \
            --package=@semantic-release/commit-analyzer          \
            --package=@semantic-release/release-notes-generator  \
            --package=@semantic-release/exec                     \
            --package=@semantic-release/git                      \
            --package=@semantic-release/github                   \
            semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
