name: verify

on:
  pull_request:
env:
  HUSKY: 0
jobs:
  commitlint:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: "11.x"
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
      - run:
          pnpm dlx commitlint -f ${{ github.event.pull_request.base.sha }} -t
          ${{ github.event.pull_request.head.sha }} -v
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          version: "0.30.1"
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -q .
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          version: "2.x"
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -c .
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: "11.x"
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
      - run: pnpm install --ignore-scripts
      - run: pnpm moonwave build
